### ISSUE TITLE
Frontend - Typescript recommendations

### ISSUE THREAD

**Issue by huygn** [dwarvesf/playbook#44]
https://github.com/dwarvesf/playbook/blob/master/engineering/frontend.md (currently outdated for the most parts).

Typescript is dominating and being used opinionatedly in most of our projects, thus some help are needed to add Typescript to polish up our Frontend practices.
@tuanddd @zlatanpham are you guys willing to help? Even just bullet points & some helpful links are good enough (more are welcome ofc), I'll look into restructuring the whole Frontend section later.

**Comment by zlatanpham** [comment]
I took the following from docs of a project. Let me know if I can help with other parts too.

TypeScript is a strict syntactical superset of JavaScript and adds optional static typing to the language. Forcing to write strongly typed syntax while you are familiar with dynamic/multi-paradigm scripting language like JavaScript is sometimes annoying, even for experienced developers. However, the drawback can be out-weighted by the following benefits when coming to write medium to large-sized applications:

- Catching your bugs at compile-time as you type them.
- Coding confidently with autocompletion, definition jumping, and source documentation.
- Syncing API Interfaces between backend and frontend via Swagger JSON docs or GraphQL code gen.
- Relieve the pain of refactoring/renaming.

### Resources

- [https://www.typescriptlang.org/](https://www.typescriptlang.org/)
- [https://github.com/DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)
- [https://basarat.gitbook.io/typescript/](https://basarat.gitbook.io/typescript/)

**Comment by zlatanpham** [comment]
I've included the TypeScript section in https://github.com/dwarvesf/playbook/pull/46
